### ISSUE TITLE
Map truffle style dependencies

### ISSUE THREAD

**Issue by shayanb** [tintinweb/vscode-solidity-auditor#2]
It is possible to import contracts using `@` which truffle pulls using `npm install`. However these contracts will be installed in `npm-modules` which truffle maps to the contract folder.

In this scenario, it is not possible to jump/see the definition of imported functions.

e.g. 
`import "@ensdomains/ens/contracts/ENS.sol";` in 
https://github.com/ensdomains/ethregistrar/blob/master/contracts/BaseRegistrarImplementation.sol

**Comment by tintinweb** [comment]
Hey @shayanb,
I've recently added some hacky magic to figure out import paths (see https://github.com/tintinweb/vscode-solidity-auditor/blob/master/src/extension.js#L52). it is already released. does this fix the issue for you

cheers,
tin

**Comment by shayanb** [comment]
Seems like this bug as it was mentioned above is fixed, however still does not jump to declaration possibly due to https://github.com/tintinweb/vscode-solidity-auditor/issues/5
