### ISSUE TITLE
graph(this) feature does not work

### ISSUE THREAD

**Issue by DryginAlexander** [tintinweb/vscode-solidity-auditor#20]
It returns only text file.
![3](https://user-images.githubusercontent.com/38461197/57930347-64b1bd00-78be-11e9-928b-c1f7dca454c9.png)
I have installed all needed extensions and surya v2.0.11. I use Ubuntu 18.04.

**Comment by tintinweb** [comment]
Hi @DryginAlexander,

Looks like something went wrong with the installation of the dot preview extension I created for solidity-visual-auditor. How it basically works is that when you install solidity-visual-auditor vscode is actually installing two extension, one is the auditor plugin itself and the other one is an interactive dot preview extension I created. If you click "graph (this)" it is running surya to generate the graph, then creates a new document and previews it in the extension - if it is installed. if not you'll get the plain graphviz dot source.

Normally vscode should take care of installing the preview extension for you as instructed in the vscode-auditor metadata.

* Please check if `Graphviz Interactive Preview` already shows up in your installed extension.
* Try to manually install: https://marketplace.visualstudio.com/items?itemName=tintinweb.graphviz-interactive-preview

let me know if that solves the problem.

cheers,
tin

**Comment by DryginAlexander** [comment]
Hi @tintinweb 
Vscode shows that the dot preview extension has been already installed. 
![1](https://user-images.githubusercontent.com/38461197/58010653-7206bb80-7af9-11e9-8a6d-5075f6fcbd90.png)

**Comment by tintinweb** [comment]
Oh, wait. It appears that the default for the auto preview is off by default (because this used to be an experimental feature). https://github.com/tintinweb/vscode-solidity-auditor/blob/master/package.json#L217-L220

Please verify that it works by switching on **solidity-va.preview.dot** in the settings. I'll release an updated version if that fixes the problem.

**Comment by DryginAlexander** [comment]
@tintinweb 

I have switched on this option and the graph features works correctly now. 

Thanks for your time!

**Comment by tintinweb** [comment]
👍
