### ISSUE TITLE
Flaterra does not support importing contracts from node_modules.

### ISSUE THREAD

**Issue by alesanro** [tintinweb/vscode-solidity-auditor#22]
Probably it will be better to use [`truffle-flattener`](https://github.com/nomiclabs/truffle-flattener) and run flattening command with `npx truffle-flattener inputfile > output`?

**Comment by tintinweb** [comment]
Hi @alesanro,

I agree we need a more consistent way for flattening files. I'll look into that, thanks for the input!

**Comment by tintinweb** [comment]
a quick update on this matter: I am going to change flaterra for the flattener extension I just published. It is just a vscode integration for `truffle-flattener`. Having this as it's own extension allows us to be more flexible in the future (and `vscode-auditor` will be able to interface with the flattener extension e.g. to flatten all top level contracts. going to merge this soon). This should close this issue.

https://marketplace.visualstudio.com/items?itemName=tintinweb.vscode-solidity-flattener
adds a context menu "flatten selected files" to the vscode explorer.
