### ISSUE TITLE
@audit-issue

### ISSUE THREAD

**Issue by rmi7** [tintinweb/vscode-solidity-auditor#23]
This is a feature request.

Next to having `@audit` and `@audit-ok`, it would be great if there was also `@audit-issue`.

this command would signify that an issue has been created in github/bitbucket, having a blue marker instead of red/green.

besides this this plugin is already amazing 👍

**Comment by tintinweb** [comment]
Hi @rmi7,

Yeah that one is totally missing :) going to ship it with the next release 👍 (including an `@audit.info` tag in blue as well or neutral color just to leave some informational notes) 

cheers

**Comment by tintinweb** [comment]
![image](https://user-images.githubusercontent.com/2865694/59918570-632b6580-9425-11e9-8ccb-e54fcb67bafc.png)

**Comment by rmi7** [comment]
great, maybe give the `info` and `issue` different colors?

**Comment by tintinweb** [comment]
I'm not good with the design parts :p 
`issue` -> purple

![image](https://user-images.githubusercontent.com/2865694/60516108-59cfb200-9cdd-11e9-9b00-887f89b4dc0e.png)
![image](https://user-images.githubusercontent.com/2865694/60516137-69e79180-9cdd-11e9-8af9-48835e134886.png)

**Comment by rmi7** [comment]
great, as long as they have a different color its fine. 👍😎

**Comment by topcook** [comment]
How can I start auditing from scratch by using this extension in vscode?
