### ISSUE TITLE
error: invalid `funcSig` output for solidity functions containing `uint` type

### ISSUE THREAD

**Issue by alesanro** [tintinweb/vscode-solidity-auditor#27]
There is an invalid hash of signature function calculation for `uint` types.

The next function has a signature `provideAccess(address[],uint256[],bytes32,bytes)` 
```solidity
function provideAccess(address[] _addresses, uint[] _amounts, bytes32 _key, bytes _info) public {
// ...
}
```

Then it should have the next hash:
```javascript
> require("web3-utils").soliditySha3("provideAccess(address[],uint256[],bytes32,bytes)").slice(0, 10)

'0x745ca7ea'
```

but `funcSig` command returns like:
```javascript
> require("web3-utils").soliditySha3("provideAccess(address[],uint[],bytes32,bytes)").slice(0, 10)

'0xb196df14'
```

**Comment by tintinweb** [comment]
thank you @alesanro!
going to merge that in a second and also fix that functions w/o arguments are actually missing. 👍
