### ISSUE TITLE
Annotations appear on words in comment blocks

### ISSUE THREAD

**Issue by akuanti** [tintinweb/vscode-solidity-auditor#3]
The extension appears to be treating comment blocks as code. For example, if I have a block like
```solidity
/**
@dev An example for this issue
*/
```
then hovering over the word "for" gives me an annotation about `LOOP - check for OOG conditions`. Similarly, I get one when hovering over the word "this."

**Comment by tintinweb** [comment]
thanks @akuanti! for performance reasons the hover decorator is treating everything as text. I'll keep this in the backlog and fix it when I have some time for it.

thx for reporting!
