### ISSUE TITLE
Should identify mappings

### ISSUE THREAD

**Issue by cleanunicorn** [tintinweb/vscode-solidity-auditor#4]
Hovering over the variable it reports

```
(undefined) StateVar StandardBounties.bounties
```

I was expecting

```
(mapping(uint => Bounty)) StateVar StandardBounties.bounties
```

![image](https://user-images.githubusercontent.com/547012/54123376-43d57300-4408-11e9-9215-5e4f1bfdff49.png)

**Comment by tintinweb** [comment]
will be available with next release 👍
